### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by jordanrule** [wright8191/flask-echo-server#3]
I see this is just a simple echo server as a sample, but have you considered adding any form of authentication?  Seems like even just a pointer could help people trying this out in the wild.

**Comment by whwright** [comment]
Did you have something specific in mind? Are you thinking you want to deploy this somewhere securely?

There is support for basic auth, but maybe that's not sufficient. This is a pretty old project at this point, but I am happy to accept PRs.

**Comment by jordanrule** [comment]
I think I found another way to do what I was looking to get done.  Thank you for maintaining this, it's an awesome starter project.
